### ISSUE TITLE
Failed to build with several errors

### ISSUE THREAD

**Issue by mingodad** [vovkos/jancy_b#2]
When trying to build this project I'm getting several errors like the one shown bellow (maybe need update submodules version ?).
```
[ 26%] Generating pch.cpp.h.gch
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/graco/samples/graco_sample_01_calc/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/graco/samples/graco_sample_01_calc/pch.h:20:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:16:
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:200:34: error: no member named 'rc' in namespace 'axl'
class NodeAllocator: public axl::rc::RefCount
                            ~~~~~^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:200:38: error: expected class name
class NodeAllocator: public axl::rc::RefCount
                                     ^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:239:7: error: no member named 'rc' in namespace 'axl'
        axl::rc::Ptr<NodeAllocator<Parser> > allocator = AXL_RC_NEW(NodeAllocator<Parser>);
        ~~~~~^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:239:37: error: expected '(' for function-style cast or type construction
        axl::rc::Ptr<NodeAllocator<Parser> > allocator = AXL_RC_NEW(NodeAllocator<Parser>);
                     ~~~~~~~~~~~~~~~~~~~~~ ^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:239:39: error: use of undeclared identifier 'allocator'
        axl::rc::Ptr<NodeAllocator<Parser> > allocator = AXL_RC_NEW(NodeAllocator<Parser>);
                                             ^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:239:83: error: expected '(' for function-style cast or type construction
        axl::rc::Ptr<NodeAllocator<Parser> > allocator = AXL_RC_NEW(NodeAllocator<Parser>);
                                                                    ~~~~~~~~~~~~~~~~~~~~~^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:240:55: error: use of undeclared identifier 'allocator'
        axl::sys::setTlsPtrSlotValue<NodeAllocator<Parser> >(allocator);
                                                             ^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:241:9: error: use of undeclared identifier 'allocator'
        return allocator;
               ^
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/graco/samples/graco_sample_01_calc/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/graco/samples/graco_sample_01_calc/pch.h:20:
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:290:9: warning: expression result unused [-Wunused-value]
                TRACE("SYMBOL STACK (%d symbols):\n", count);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:296:10: warning: expression result unused [-Wunused-value]
                        TRACE("%p %s", node, static_cast<T*>(this)->getSymbolName(node->m_index));
                              ^~~~~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:297:10: warning: expression result unused [-Wunused-value]
                        TRACE(" (%d:%d)", value->m_firstTokenPos.m_line + 1, value->m_firstTokenPos.m_col + 1);
                              ^~~~~~~~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:297:52: warning: expression result unused [-Wunused-value]
                        TRACE(" (%d:%d)", value->m_firstTokenPos.m_line + 1, value->m_firstTokenPos.m_col + 1);
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:306:9: warning: expression result unused [-Wunused-value]
                TRACE("PREDICTION STACK (%d nodes):\n", count);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:316:10: warning: expression result unused [-Wunused-value]
                        TRACE("%p %s (%d) %s\n", node, getNodeKindString(node->m_nodeKind), node->m_index, extra);
                              ^~~~~~~~~~~~~~~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:316:29: warning: expression result unused [-Wunused-value]
                        TRACE("%p %s (%d) %s\n", node, getNodeKindString(node->m_nodeKind), node->m_index, extra);
                                                 ^~~~
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:316:78: warning: expression result unused [-Wunused-value]
                        TRACE("%p %s (%d) %s\n", node, getNodeKindString(node->m_nodeKind), node->m_index, extra);
                                                                                            ~~~~  ^~~~~~~
8 warnings and 8 errors generated.
graco/samples/graco_sample_01_calc/CMakeFiles/graco_sample_01_calc_pch.dir/build.make:61: recipe for target 'graco/samples/graco_sample_01_calc/pch.cpp.h.gch' failed
make[2]: *** [graco/samples/graco_sample_01_calc/pch.cpp.h.gch] Error 1
CMakeFiles/Makefile2:2246: recipe for target 'graco/samples/graco_sample_01_calc/CMakeFiles/graco_sample_01_calc_pch.dir/all' failed
make[1]: *** [graco/samples/graco_sample_01_calc/CMakeFiles/graco_sample_01_calc_pch.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mingodad** [comment]
Sorry! My bad it was my fault because I didn't executed `git submodule update`.

**Comment by mingodad** [comment]
But it still fail the install with the error shown bellow (it seems that now there is a dedicated folder `/axl_re/`)
```
-- Up-to-date: /home/mingo/local/jancy/include/axl/axl_re_Match.h
CMake Error at axl/src/axl_re/cmake_install.cmake:61 (file):
  file INSTALL cannot find
  "/home/mingo/dev/c/A_programming-languages/jancy_b0/axl/include/axl_re_StateInit.h".
Call Stack (most recent call first):
  axl/src/cmake_install.cmake:47 (include)
  axl/cmake_install.cmake:47 (include)
  cmake_install.cmake:42 (include)
```

**Comment by vovkos** [comment]
There were a bunch of install-related CMake issues; fixed. Also, updated Jancy to compile with newest LLVMs (from LLVM-3.4.2 all the way up to LLVM-16).

**Comment by mingodad** [comment]
Testing on Ubuntu 18.04 64 bits with:
Clang 3.4.2 / 3.5.2 / 5.0.2 / 6.0.1 / 7.0.1 / 8.0.0 / 9.0.1 / 10.0.0 / 11.0.1 / 12.0.1 / 13.0.1 :
```
...
[  2%] Generating pch.cpp.h.gch
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/jancy/src/jnc_ct/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/pch.h:20:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Parser.h:16:
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:200:34: error: no member named 'rc' in
      namespace 'axl'
class NodeAllocator: public axl::rc::RefCount
                            ~~~~~^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:200:38: error: expected class name
class NodeAllocator: public axl::rc::RefCount
                                     ^
/home/mingo/dev/c/A_programming-languages/jancy_b/graco/include/llk_Node.h:239:7: error: no member named 'rc' in
      namespace 'axl'
        axl::rc::Ptr<NodeAllocator<Parser> > allocator = AXL_RC_NEW(NodeAllocator<Parser>);
        ~~~~~^
...
```
Clang 3.6:
```
...
-- Graco 1.3.3 paths:
--     CMake files:         /home/mingo/dev/c/A_programming-languages/jancy_b/graco/cmake
--                          /home/mingo/dev/c/A_programming-languages/jancy_b/graco/cmake
--     Includes:            /home/mingo/dev/c/A_programming-languages/jancy_b/graco/include
--     Frames:              /home/mingo/dev/c/A_programming-languages/jancy_b/graco/frame
--     Executable:          /home/mingo/dev/c/A_programming-languages/jancy_b/graco/bin/Release/graco
CMake Error at axl/cmake/import_llvm.cmake:53 (llvm_map_components_to_libnames):
  Unknown CMake command "llvm_map_components_to_libnames".
Call Stack (most recent call first):
  axl/cmake/import_llvm.cmake:80 (target_link_llvm_libraries)
  jancy/src/jnc_dll/CMakeLists.txt:106 (target_link_llvm_jit_libraries)


-- Configuring incomplete, errors occurred!
See also "/home/mingo/dev/c/A_programming-languages/jancy_b/build/CMakeFiles/CMakeOutput.log".
...
```
Clang 14.0.0 / 15.0.7:
```
...
[  2%] Generating pch.cpp.h.gch
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/jancy/src/jnc_ct/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/pch.h:16:
/home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/include/jnc_ct_Pch.h:78:10: fatal error: 'llvm/Support/TargetRegistry.h' file not found
#include <llvm/Support/TargetRegistry.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
jancy/src/jnc_ct/CMakeFiles/jnc_ct_pch.dir/build.make:73: recipe for target 'jancy/src/jnc_ct/pch.cpp.h.gch' failed
...
```
Clang 16.0.0:
```
[  2%] Generating pch.cpp.h.gch
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/jancy/src/jnc_ct/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/pch.h:16:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/include/jnc_ct_Pch.h:55:
In file included from /home/mingo/local/clang-16/include/llvm/IR/LLVMContext.h:18:
In file included from /home/mingo/local/clang-16/include/llvm/IR/DiagnosticHandler.h:15:
In file included from /home/mingo/local/clang-16/include/llvm/ADT/StringRef.h:12:
/home/mingo/local/clang-16/include/llvm/ADT/DenseMapInfo.h:294:52: error: no member named 'variant' in namespace 'std'
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                              ~~~~~^
/home/mingo/local/clang-16/include/llvm/ADT/DenseMapInfo.h:294:60: error: 'Ts' does not refer to a value
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                                           ^
/home/mingo/local/clang-16/include/llvm/ADT/DenseMapInfo.h:294:23: note: declared here
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                      ^
/home/mingo/local/clang-16/include/llvm/ADT/DenseMapInfo.h:294:66: error: expected unqualified-id
template <typename... Ts> struct DenseMapInfo<std::variant<Ts...>> {
                                                                 ^
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/build/jancy/src/jnc_ct/pch.cpp.h:1:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/pch.h:16:
In file included from /home/mingo/dev/c/A_programming-languages/jancy_b/jancy/src/jnc_ct/include/jnc_ct_Pch.h:55:
In file included from /home/mingo/local/clang-16/include/llvm/IR/LLVMContext.h:18:
In file included from /home/mingo/local/clang-16/include/llvm/IR/DiagnosticHandler.h:15:
In file included from /home/mingo/local/clang-16/include/llvm/ADT/StringRef.h:13:
In file included from /home/mingo/local/clang-16/include/llvm/ADT/STLFunctionalExtras.h:18:
/home/mingo/local/clang-16/include/llvm/ADT/STLForwardCompat.h:46:35: error: no template named 'optional' in namespace 'std'
auto transformOptional(const std::optional<T> &O, const Function &F)
                             ~~~~~^
/home/mingo/local/clang-16/include/llvm/ADT/STLForwardCompat.h:47:13: error: no template named 'optional' in namespace 'std'
    -> std::optional<decltype(F(*O))> {
       ~~~~~^
/home/mingo/local/clang-16/include/llvm/ADT/STLForwardCompat.h:50:15: error: no member named 'nullopt' in namespace 'std'
  return std::nullopt;
         ~~~~~^
/home/mingo/local/clang-16/include/llvm/ADT/STLForwardCompat.h:56:6: error: redefinition of 'transformOptional' as different kind of symbol
auto transformOptional(std::optional<T> &&O, const Function &F)
     ^
/home/mingo/local/clang-16/include/llvm/ADT/STLForwardCompat.h:46:6: note: previous definition is here
auto transformOptional(const std::optional<T> &O, const Function &F)
```
```
uname -a
Linux mingo-X550VX 5.4.0-137-generic #154~18.04.1-Ubuntu SMP Tue Jan 10 16:58:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
...
cmake --version
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by mingodad** [comment]
Sorry again !
After `git submodule update` it's building now with clang-15.

**Comment by mingodad** [comment]
Maybe somehow adding `git submodule init/update` to `CMakeList.txt` would prevent more headaches for both users and you ?
